[phases.setup]
nixPkgs = [
  "php83",
<<<<<<< HEAD
  "php83Packages.composer",
=======
>>>>>>> 42dd632e8e90f0c6ee4d64607e37e9ec8560c5fe
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.zip",
  "php83Extensions.gd",
  "php83Extensions.opcache",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "php83Extensions.ctype",
  "php83Extensions.curl",
  "nodejs_20",
]
